SET HEADING OFF;

SELECT 'DEPNUM'
  || '; DEPNAME'
  || '; FILIAL'
  || '; SHORTNAME'
  || ';'
FROM DEPARTMENTS ROWS 1;

SELECT  '"' || REPLACE(TRIM(COALESCE(DEPNUM, '')), '"', '""')
  || '"; "' || REPLACE(TRIM(COALESCE(DEPNAME, '')), '"', '""')
  || '"; "' || REPLACE(TRIM(COALESCE(FILIAL, '')), '"', '""')
  || '"; "' || REPLACE(TRIM(COALESCE(DEPARTMENTS.SHORTNAME, '')), '"', '""')
  || '";'
FROM DEPARTMENTS INNER JOIN FILIALS on FILIALS.FILID = DEPARTMENTS.FILIAL
where FILIALS.VIEWINWEB = 1
;
